language: elixir
elixir:
  - 1.5
otp_release:
  - 20.2

cache: apt

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, test

# after_success:
#   - test $TRAVIS_BRANCH = "master" && ./publish_to_hex.sh
